language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: xenial
      compiler: g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"

script:
- cmake -DCMAKE_BUILD_TYPE=Release && make
